import type { Meal } from './types'

/* 15 comidas DEMO. Marcadas con isDemo para poder borrarlas todas juntas
   cuando entren los datos reales. Los carbohidratos son valores de referencia,
   no verdad nutricional: la fuente y la confianza se muestran siempre. */

export const DEMO_MEALS: Meal[] = [
  /* ---------------- DESAYUNO ---------------- */
  {
    id: 'm-oats',
    name: 'Overnight oats con banana y nueces',
    category: 'desayuno',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'avena',
    ingredients: ['Avena 60 g', 'Yogur natural 150 g', 'Leche 80 ml', 'Banana 1', 'Nueces 20 g', 'Canela'],
    portion: '1 frasco de 400 ml',
    carbs: 58,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 8,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'Aguanta bien hasta el mediodía. Si el día es largo, sumar una cucharada más de nueces.',
    prepSteps: ['Armar overnight oats en el frasco', 'Cortar banana'],
    isDemo: true,
  },
  {
    id: 'm-sandwich',
    name: 'Sándwich completo',
    category: 'desayuno',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Pan integral 2 rebanadas', 'Huevo 2', 'Queso port salut 40 g', 'Tomate', 'Palta ½'],
    portion: '1 sándwich',
    carbs: 46,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 12,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'Poner la palta a último momento o pincelarla con limón.',
    prepSteps: ['Armar sándwich completo', 'Hervir huevos'],
    isDemo: true,
  },
  {
    id: 'm-tortilla',
    name: 'Tortilla de papa en tupper',
    category: 'desayuno',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'huevo',
    ingredients: ['Papa 2 medianas', 'Huevo 4', 'Cebolla ½', 'Aceite de oliva'],
    portion: '2 porciones (rinde para 2 días)',
    carbs: 34,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 30,
    satiety: 'normal',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: true,
    difficulty: 2,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Se come fría sin problema. Rinde dos días.',
    prepSteps: ['Hacer tortilla de papa', 'Porcionar en tuppers'],
    isDemo: true,
  },
  {
    id: 'm-tostadas-huevo',
    name: 'Tostadas con huevo revuelto, queso y tomate',
    category: 'desayuno',
    tags: ['en casa', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Pan 2 rebanadas', 'Huevo 3', 'Queso 40 g', 'Tomate', 'Aceite de oliva'],
    portion: '1 plato',
    carbs: 38,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 10,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    isDemo: true,
  },
  {
    id: 'm-yogur-granola',
    name: 'Yogur con granola',
    category: 'desayuno',
    tags: ['emergencia', 'rápido', 'liviano'],
    mainIngredient: 'yogur',
    ingredients: ['Yogur entero 200 g', 'Granola 40 g'],
    portion: '1 pote + 1 puñado',
    carbs: 44,
    carbSource: 'etiqueta',
    confidence: 'alta',
    prepMinutes: 2,
    satiety: 'liviana',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 3,
    notes: 'Plan de emergencia: cero preparación. No aguanta muchas horas.',
    isDemo: true,
  },

  /* ---------------- SNACK ---------------- */
  {
    id: 'm-nueces',
    name: 'Nueces y almendras',
    category: 'snack',
    tags: ['para llevar', 'liviano', 'rápido'],
    mainIngredient: 'frutos secos',
    ingredients: ['Nueces 15 g', 'Almendras 15 g'],
    portion: '1 puñado (30 g)',
    carbs: 4,
    carbSource: 'etiqueta',
    confidence: 'alta',
    prepMinutes: 2,
    satiety: 'liviana',
    portable: true,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 4,
    prepSteps: ['Porcionar frutos secos'],
    isDemo: true,
  },
  {
    id: 'm-manzana-mani',
    name: 'Manzana con mantequilla de maní',
    category: 'snack',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'fruta',
    ingredients: ['Manzana 1', 'Mantequilla de maní 20 g'],
    portion: '1 manzana + 1 cucharada',
    carbs: 24,
    carbSource: 'estimación',
    confidence: 'estimada',
    prepMinutes: 3,
    satiety: 'normal',
    portable: true,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Confirmar los carbos con la etiqueta del frasco de maní.',
    prepSteps: ['Lavar fruta'],
    isDemo: true,
  },
  {
    id: 'm-mini-sandwich',
    name: 'Mini sándwich de queso y jamón',
    category: 'snack',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'pan',
    ingredients: ['Pan de salvado 1 rebanada', 'Queso 30 g', 'Jamón 30 g'],
    portion: '1 mini sándwich',
    carbs: 22,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 5,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Para cuando el almuerzo fue chico o faltan muchas horas.',
    prepSteps: ['Armar mini sándwich'],
    isDemo: true,
  },

  /* ---------------- ALMUERZO ---------------- */
  {
    id: 'm-pollo-arroz',
    name: 'Pollo al horno con arroz y ensalada',
    category: 'almuerzo',
    tags: ['en casa', 'potente'],
    mainIngredient: 'pollo',
    ingredients: ['Pechuga de pollo 200 g', 'Arroz 70 g en crudo', 'Tomate', 'Lechuga', 'Aceite de oliva'],
    portion: '1 plato',
    carbs: 58,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 40,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: true,
    makeNightBefore: true,
    freezable: true,
    difficulty: 2,
    favorite: true,
    tested: true,
    rating: 5,
    prepSteps: ['Cocinar pollo', 'Hacer arroz', 'Armar tupper de almuerzo'],
    isDemo: true,
  },
  {
    id: 'm-wrap-pollo',
    name: 'Wrap de pollo y vegetales',
    category: 'almuerzo',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'pollo',
    ingredients: ['Tortilla de trigo 1', 'Pollo 150 g', 'Lechuga', 'Tomate', 'Zanahoria', 'Yogur natural 2 cdas'],
    portion: '1 wrap grande',
    carbs: 42,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 15,
    satiety: 'normal',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 4,
    notes: 'Envolver en papel manteca para que no se abra en la mochila.',
    prepSteps: ['Cocinar pollo', 'Armar wrap'],
    isDemo: true,
  },
  {
    id: 'm-lentejas',
    name: 'Ensalada de lentejas con huevo y palta',
    category: 'almuerzo',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'lentejas',
    ingredients: ['Lentejas cocidas 200 g', 'Huevo 2', 'Palta ½', 'Cebolla morada', 'Tomate', 'Limón'],
    portion: '1 tupper grande',
    carbs: 40,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 20,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Se come fría. Muy buena para días de mucho movimiento.',
    prepSteps: ['Hervir huevos', 'Armar tupper de almuerzo'],
    isDemo: true,
  },

  /* ---------------- MERIENDA ---------------- */
  {
    id: 'm-tostadas-queso',
    name: 'Tostadas con queso y tomate + café',
    category: 'merienda',
    tags: ['en casa', 'normal', 'rápido'],
    mainIngredient: 'pan',
    ingredients: ['Pan 2 rebanadas', 'Queso 50 g', 'Tomate', 'Café con leche'],
    portion: '2 tostadas + 1 taza',
    carbs: 32,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 7,
    satiety: 'normal',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    isDemo: true,
  },
  {
    id: 'm-omelette',
    name: 'Omelette de espinaca y queso con pan',
    category: 'merienda',
    tags: ['en casa', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Huevo 3', 'Espinaca 1 puñado', 'Queso 40 g', 'Pan 1 rebanada'],
    portion: '1 omelette',
    carbs: 20,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 12,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'Para cuando la cena va a ser tarde o el almuerzo fue temprano.',
    isDemo: true,
  },

  /* ---------------- CENA ---------------- */
  {
    id: 'm-milanesa',
    name: 'Milanesa de pollo al horno con puré de calabaza',
    category: 'cena',
    tags: ['en casa', 'potente'],
    mainIngredient: 'pollo',
    ingredients: ['Milanesa de pollo 2', 'Calabaza 400 g', 'Aceite de oliva', 'Ensalada verde'],
    portion: '1 plato',
    carbs: 45,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 35,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: true,
    makeNightBefore: false,
    freezable: true,
    difficulty: 2,
    favorite: false,
    tested: true,
    rating: 4,
    isDemo: true,
  },
  {
    id: 'm-revuelto',
    name: 'Revuelto de zapallitos con huevo',
    category: 'cena',
    tags: ['en casa', 'liviano', 'rápido'],
    mainIngredient: 'huevo',
    ingredients: ['Zapallitos 2', 'Huevo 3', 'Cebolla ½', 'Pan 1 rebanada'],
    portion: '1 plato',
    carbs: 18,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 15,
    satiety: 'normal',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Cena liviana para cuando se come tarde.',
    isDemo: true,
  },
]
