import type { Meal } from './types'

/* ------------------------------------------------------------------
   DATOS DE DEMOSTRACIÓN — NO SON DATOS REALES

   Estas comidas existen sólo para que la interfaz tenga algo que mostrar
   y para poder probar la rotación con los seis momentos del día.

   Los carbohidratos NO están verificados: son valores plausibles, no
   medidos. Por eso todas llevan carbsVerified: false, y la app las marca
   como DEMO en todas las pantallas y muestra el carbo como sin confirmar,
   ignorando el carbSource / confidence que tengan cargado.

   Esos dos campos quedan con valores variados a propósito: el día que una
   comida real se marque carbsVerified: true, el sistema de confianza
   (alta / media / estimada) se enciende solo, sin tocar ninguna pantalla.

   La biblioteca real la vamos a construir comida por comida.
   ------------------------------------------------------------------ */

const demo = (m: Omit<Meal, 'isDemo' | 'carbsVerified'>): Meal => ({
  ...m,
  carbsVerified: false,
  isDemo: true,
})

export const DEMO_MEALS: Meal[] = [
  /* ---------------- DESAYUNO ---------------- */
  demo({
    id: 'm-oats',
    name: 'Overnight oats con banana y nueces',
    category: 'desayuno',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'avena',
    ingredients: ['Avena 60 g', 'Yogur natural 150 g', 'Leche 80 ml', 'Banana 1', 'Nueces 20 g', 'Canela'],
    portion: '1 frasco de 400 ml',
    carbs: 58,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 8,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'Aguanta bien hasta el mediodía.',
    prepSteps: ['Armar overnight oats en el frasco', 'Cortar banana'],
  }),
  demo({
    id: 'm-sandwich',
    name: 'Sándwich completo',
    category: 'desayuno',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Pan integral 2 rebanadas', 'Huevo 2', 'Queso port salut 40 g', 'Tomate', 'Palta ½'],
    portion: '1 sándwich',
    carbs: 46,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 12,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'La palta, a último momento o con limón.',
    prepSteps: ['Armar sándwich completo', 'Hervir huevos'],
  }),
  demo({
    id: 'm-muffins',
    name: 'Muffins salados de huevo, queso y espinaca',
    category: 'desayuno',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Huevo 6', 'Queso 80 g', 'Espinaca 2 puñados', 'Harina integral 40 g'],
    portion: '3 muffins (rinde 6)',
    carbs: 22,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 30,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: true,
    difficulty: 2,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Rinden dos días y se congelan bien.',
    prepSteps: ['Hornear muffins salados', 'Porcionar en tuppers'],
  }),
  demo({
    id: 'm-tortilla',
    name: 'Tortilla de papa en tupper',
    category: 'desayuno',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'papa',
    ingredients: ['Papa 2 medianas', 'Huevo 4', 'Cebolla ½', 'Aceite de oliva'],
    portion: '2 porciones (rinde para 2 días)',
    carbs: 34,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 30,
    satiety: 'normal',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: true,
    difficulty: 2,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Se come fría sin problema.',
    prepSteps: ['Hacer tortilla de papa', 'Porcionar en tuppers'],
  }),
  demo({
    id: 'm-tostadas-huevo',
    name: 'Tostadas con huevo revuelto, queso y tomate',
    category: 'desayuno',
    tags: ['en casa', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Pan 2 rebanadas', 'Huevo 3', 'Queso 40 g', 'Tomate', 'Aceite de oliva'],
    portion: '1 plato',
    carbs: 38,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 10,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
  }),
  demo({
    id: 'm-yogur-granola',
    name: 'Yogur con granola',
    category: 'desayuno',
    tags: ['emergencia', 'rápido', 'liviano'],
    mainIngredient: 'yogur',
    ingredients: ['Yogur entero 200 g', 'Granola 40 g'],
    portion: '1 pote + 1 puñado',
    carbs: 44,
    carbSource: 'etiqueta',
    confidence: 'alta',
    prepMinutes: 2,
    satiety: 'liviana',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 3,
    notes: 'Plan de emergencia: cero preparación. No aguanta muchas horas.',
  }),

  /* ---------------- SNACK ---------------- */
  demo({
    id: 'm-nueces',
    name: 'Nueces y almendras',
    category: 'snack',
    tags: ['para llevar', 'liviano', 'rápido'],
    mainIngredient: 'frutos secos',
    ingredients: ['Nueces 15 g', 'Almendras 15 g'],
    portion: '1 puñado (30 g)',
    carbs: 4,
    carbSource: 'etiqueta',
    confidence: 'alta',
    prepMinutes: 2,
    satiety: 'liviana',
    portable: true,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 4,
    prepSteps: ['Porcionar frutos secos'],
  }),
  demo({
    id: 'm-manzana-mani',
    name: 'Manzana con mantequilla de maní',
    category: 'snack',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'fruta',
    ingredients: ['Manzana 1', 'Mantequilla de maní 20 g'],
    portion: '1 manzana + 1 cucharada',
    carbs: 24,
    carbSource: 'estimación',
    confidence: 'estimada',
    prepMinutes: 3,
    satiety: 'normal',
    portable: true,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    prepSteps: ['Lavar fruta'],
  }),
  demo({
    id: 'm-huevos-queso',
    name: 'Huevos duros con queso en cubos',
    category: 'snack',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Huevo 2', 'Queso 40 g'],
    portion: '1 tupper chico',
    carbs: 3,
    carbSource: 'estimación',
    confidence: 'estimada',
    prepMinutes: 10,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Casi sin carbos. Sirve cuando faltan muchas horas para comer.',
    prepSteps: ['Hervir huevos'],
  }),
  demo({
    id: 'm-mini-sandwich',
    name: 'Mini sándwich de queso y jamón',
    category: 'snack',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'pan',
    ingredients: ['Pan de salvado 1 rebanada', 'Queso 30 g', 'Jamón 30 g'],
    portion: '1 mini sándwich',
    carbs: 22,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 5,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    prepSteps: ['Armar mini sándwich'],
  }),

  /* ---------------- ALMUERZO ---------------- */
  demo({
    id: 'm-pollo-arroz',
    name: 'Pollo al horno con arroz y ensalada',
    category: 'almuerzo',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'pollo',
    ingredients: ['Pechuga de pollo 200 g', 'Arroz 70 g en crudo', 'Tomate', 'Lechuga', 'Aceite de oliva'],
    portion: '1 tupper grande',
    carbs: 58,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 40,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: true,
    makeNightBefore: true,
    freezable: true,
    difficulty: 2,
    favorite: true,
    tested: true,
    rating: 5,
    prepSteps: ['Cocinar pollo', 'Hacer arroz', 'Armar tupper de almuerzo'],
  }),
  demo({
    id: 'm-wrap-pollo',
    name: 'Wrap de pollo y vegetales',
    category: 'almuerzo',
    tags: ['para llevar', 'normal'],
    mainIngredient: 'pollo',
    ingredients: ['Tortilla de trigo 1', 'Pollo 150 g', 'Lechuga', 'Tomate', 'Zanahoria', 'Yogur natural 2 cdas'],
    portion: '1 wrap grande',
    carbs: 42,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 15,
    satiety: 'normal',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 4,
    notes: 'Envolver en papel manteca para que no se abra en la mochila.',
    prepSteps: ['Cocinar pollo', 'Armar wrap'],
  }),
  demo({
    id: 'm-lentejas',
    name: 'Ensalada de lentejas con huevo y palta',
    category: 'almuerzo',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'lentejas',
    ingredients: ['Lentejas cocidas 200 g', 'Huevo 2', 'Palta ½', 'Cebolla morada', 'Tomate', 'Limón'],
    portion: '1 tupper grande',
    carbs: 40,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 20,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Se come fría. Muy buena para días de mucho movimiento.',
    prepSteps: ['Hervir huevos', 'Armar tupper de almuerzo'],
  }),
  demo({
    id: 'm-arroz-atun',
    name: 'Arroz con atún, huevo y vegetales',
    category: 'almuerzo',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'atún',
    ingredients: ['Arroz 70 g en crudo', 'Atún al natural 1 lata', 'Huevo 1', 'Choclo', 'Morrón', 'Mayonesa 1 cda'],
    portion: '1 tupper grande',
    carbs: 62,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 25,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Se come frío. Sale rápido si el arroz ya está hecho.',
    prepSteps: ['Hacer arroz', 'Hervir huevos', 'Armar tupper de almuerzo'],
  }),

  /* ---------------- MERIENDA ----------------
     La merienda es una comida, no un snack: puede ser bastante fuerte. */
  demo({
    id: 'm-tostadas-queso',
    name: 'Tostadas con queso y tomate + café',
    category: 'merienda',
    tags: ['en casa', 'normal', 'rápido'],
    mainIngredient: 'pan',
    ingredients: ['Pan 2 rebanadas', 'Queso 50 g', 'Tomate', 'Café con leche'],
    portion: '2 tostadas + 1 taza',
    carbs: 32,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 7,
    satiety: 'normal',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
  }),
  demo({
    id: 'm-omelette',
    name: 'Omelette de espinaca y queso con pan',
    category: 'merienda',
    tags: ['en casa', 'potente'],
    mainIngredient: 'huevo',
    ingredients: ['Huevo 3', 'Espinaca 1 puñado', 'Queso 40 g', 'Pan 1 rebanada'],
    portion: '1 omelette',
    carbs: 20,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 12,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 5,
    notes: 'Para cuando la cena va a ser tarde.',
  }),
  demo({
    id: 'm-sandwich-merienda',
    name: 'Sándwich de queso, tomate y huevo',
    category: 'merienda',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'pan',
    ingredients: ['Pan integral 2 rebanadas', 'Queso 50 g', 'Huevo 1', 'Tomate', 'Orégano'],
    portion: '1 sándwich',
    carbs: 40,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 10,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Merienda de verdad para los días en la calle.',
    prepSteps: ['Hervir huevos', 'Armar sándwich de merienda'],
  }),
  demo({
    id: 'm-yogur-completo',
    name: 'Yogur completo con avena, fruta y nueces',
    category: 'merienda',
    tags: ['para llevar', 'potente'],
    mainIngredient: 'yogur',
    ingredients: ['Yogur entero 250 g', 'Avena 40 g', 'Frutilla o banana', 'Nueces 20 g'],
    portion: '1 frasco grande',
    carbs: 52,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 6,
    satiety: 'potente',
    portable: true,
    needsCold: true,
    needsReheat: false,
    makeNightBefore: true,
    freezable: false,
    difficulty: 1,
    favorite: true,
    tested: true,
    rating: 4,
    prepSteps: ['Armar frasco de yogur', 'Lavar fruta'],
  }),

  /* ---------------- CENA ---------------- */
  demo({
    id: 'm-milanesa',
    name: 'Milanesa de pollo al horno con puré de calabaza',
    category: 'cena',
    tags: ['en casa', 'potente'],
    mainIngredient: 'pollo',
    ingredients: ['Milanesa de pollo 2', 'Calabaza 400 g', 'Aceite de oliva', 'Ensalada verde'],
    portion: '1 plato',
    carbs: 45,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 35,
    satiety: 'potente',
    portable: false,
    needsCold: false,
    needsReheat: true,
    makeNightBefore: false,
    freezable: true,
    difficulty: 2,
    favorite: false,
    tested: true,
    rating: 4,
  }),
  demo({
    id: 'm-revuelto',
    name: 'Revuelto de zapallitos con huevo',
    category: 'cena',
    tags: ['en casa', 'rápido', 'liviano'],
    mainIngredient: 'huevo',
    ingredients: ['Zapallitos 2', 'Huevo 3', 'Cebolla ½', 'Pan 1 rebanada'],
    portion: '1 plato',
    carbs: 18,
    carbSource: 'receta',
    confidence: 'alta',
    prepMinutes: 15,
    satiety: 'normal',
    portable: false,
    needsCold: false,
    needsReheat: false,
    makeNightBefore: false,
    freezable: false,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 4,
    notes: 'Cena liviana para cuando se come tarde.',
  }),
  demo({
    id: 'm-sopa-calabaza',
    name: 'Sopa crema de calabaza con pan y queso',
    category: 'cena',
    tags: ['en casa', 'normal'],
    mainIngredient: 'calabaza',
    ingredients: ['Calabaza 500 g', 'Cebolla 1', 'Caldo', 'Pan 1 rebanada', 'Queso 40 g'],
    portion: '1 plato hondo',
    carbs: 34,
    carbSource: 'receta',
    confidence: 'media',
    prepMinutes: 30,
    satiety: 'normal',
    portable: false,
    needsCold: false,
    needsReheat: true,
    makeNightBefore: false,
    freezable: true,
    difficulty: 1,
    favorite: false,
    tested: true,
    rating: 3,
  }),
]
